[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "altanalyze3"
authors = [{name = "AltAnalyze", email = "altanalyze@gmail.com"}]
dynamic = ["version", "description"]
